USE w3schools;
DESC MyTable13;
-- MODIFY COLUMN : 컬럼 타입 변경
ALTER TABLE MyTable13 
MODIFY COLUMN Col20 VARCHAR(40);

SELECT * FROM MyTable13;
ALTER TABLE MyTable13
MODIFY COLUMN Col13 VARCHAR(3); -- 위험!!!

-- 연습) 아무 컬럼이나 타입 변경
ALTER TABLE MyTable13
MODIFY COLUMN Col7 INT;

--
ALTER TABLE MyTable13
MODIFY COLUMN Col8 VARCHAR(9) FIRST;
DESC MyTable13;
ALTER TABLE MyTable13
MODIFY COLUMN Col8 VARCHAR(9) AFTER Col6;

-- 연습) MyTable13의 아무 컬럼의 위치 변경
ALTER TABLE MyTable13
MODIFY COLUMN Col4 VARCHAR(9) AFTER Col8;